/* soapH.h
   Generated by gSOAP 2.7.10 from captureGSOAP.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__openDocument
#define SOAP_TYPE_ns__openDocument (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__openDocument(struct soap*, struct ns__openDocument *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__openDocument(struct soap*, const struct ns__openDocument *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__openDocument(struct soap*, const struct ns__openDocument *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__openDocument(struct soap*, const char*, int, const struct ns__openDocument *, const char*);
SOAP_FMAC3 struct ns__openDocument * SOAP_FMAC4 soap_get_ns__openDocument(struct soap*, struct ns__openDocument *, const char*, const char*);
SOAP_FMAC3 struct ns__openDocument * SOAP_FMAC4 soap_in_ns__openDocument(struct soap*, const char*, struct ns__openDocument *, const char*);
SOAP_FMAC5 struct ns__openDocument * SOAP_FMAC6 soap_new_ns__openDocument(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__openDocument(struct soap*, struct ns__openDocument*);
SOAP_FMAC3 struct ns__openDocument * SOAP_FMAC4 soap_instantiate_ns__openDocument(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__openDocument(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__openDocumentResponse
#define SOAP_TYPE_ns__openDocumentResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__openDocumentResponse(struct soap*, struct ns__openDocumentResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__openDocumentResponse(struct soap*, const struct ns__openDocumentResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__openDocumentResponse(struct soap*, const struct ns__openDocumentResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__openDocumentResponse(struct soap*, const char*, int, const struct ns__openDocumentResponse *, const char*);
SOAP_FMAC3 struct ns__openDocumentResponse * SOAP_FMAC4 soap_get_ns__openDocumentResponse(struct soap*, struct ns__openDocumentResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__openDocumentResponse * SOAP_FMAC4 soap_in_ns__openDocumentResponse(struct soap*, const char*, struct ns__openDocumentResponse *, const char*);
SOAP_FMAC5 struct ns__openDocumentResponse * SOAP_FMAC6 soap_new_ns__openDocumentResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__openDocumentResponse(struct soap*, struct ns__openDocumentResponse*);
SOAP_FMAC3 struct ns__openDocumentResponse * SOAP_FMAC4 soap_instantiate_ns__openDocumentResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__openDocumentResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__sendMIME
#define SOAP_TYPE_ns__sendMIME (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__sendMIME(struct soap*, struct ns__sendMIME *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__sendMIME(struct soap*, const struct ns__sendMIME *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__sendMIME(struct soap*, const struct ns__sendMIME *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__sendMIME(struct soap*, const char*, int, const struct ns__sendMIME *, const char*);
SOAP_FMAC3 struct ns__sendMIME * SOAP_FMAC4 soap_get_ns__sendMIME(struct soap*, struct ns__sendMIME *, const char*, const char*);
SOAP_FMAC3 struct ns__sendMIME * SOAP_FMAC4 soap_in_ns__sendMIME(struct soap*, const char*, struct ns__sendMIME *, const char*);
SOAP_FMAC5 struct ns__sendMIME * SOAP_FMAC6 soap_new_ns__sendMIME(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__sendMIME(struct soap*, struct ns__sendMIME*);
SOAP_FMAC3 struct ns__sendMIME * SOAP_FMAC4 soap_instantiate_ns__sendMIME(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__sendMIME(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__sendMIMEResponse
#define SOAP_TYPE_ns__sendMIMEResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__sendMIMEResponse(struct soap*, struct ns__sendMIMEResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__sendMIMEResponse(struct soap*, const struct ns__sendMIMEResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__sendMIMEResponse(struct soap*, const struct ns__sendMIMEResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__sendMIMEResponse(struct soap*, const char*, int, const struct ns__sendMIMEResponse *, const char*);
SOAP_FMAC3 struct ns__sendMIMEResponse * SOAP_FMAC4 soap_get_ns__sendMIMEResponse(struct soap*, struct ns__sendMIMEResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__sendMIMEResponse * SOAP_FMAC4 soap_in_ns__sendMIMEResponse(struct soap*, const char*, struct ns__sendMIMEResponse *, const char*);
SOAP_FMAC5 struct ns__sendMIMEResponse * SOAP_FMAC6 soap_new_ns__sendMIMEResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__sendMIMEResponse(struct soap*, struct ns__sendMIMEResponse*);
SOAP_FMAC3 struct ns__sendMIMEResponse * SOAP_FMAC4 soap_instantiate_ns__sendMIMEResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__sendMIMEResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__receiveFileBase64
#define SOAP_TYPE_ns__receiveFileBase64 (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__receiveFileBase64(struct soap*, struct ns__receiveFileBase64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__receiveFileBase64(struct soap*, const struct ns__receiveFileBase64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__receiveFileBase64(struct soap*, const struct ns__receiveFileBase64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__receiveFileBase64(struct soap*, const char*, int, const struct ns__receiveFileBase64 *, const char*);
SOAP_FMAC3 struct ns__receiveFileBase64 * SOAP_FMAC4 soap_get_ns__receiveFileBase64(struct soap*, struct ns__receiveFileBase64 *, const char*, const char*);
SOAP_FMAC3 struct ns__receiveFileBase64 * SOAP_FMAC4 soap_in_ns__receiveFileBase64(struct soap*, const char*, struct ns__receiveFileBase64 *, const char*);
SOAP_FMAC5 struct ns__receiveFileBase64 * SOAP_FMAC6 soap_new_ns__receiveFileBase64(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__receiveFileBase64(struct soap*, struct ns__receiveFileBase64*);
SOAP_FMAC3 struct ns__receiveFileBase64 * SOAP_FMAC4 soap_instantiate_ns__receiveFileBase64(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__receiveFileBase64(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__sendFileBase64
#define SOAP_TYPE_ns__sendFileBase64 (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__sendFileBase64(struct soap*, struct ns__sendFileBase64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__sendFileBase64(struct soap*, const struct ns__sendFileBase64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__sendFileBase64(struct soap*, const struct ns__sendFileBase64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__sendFileBase64(struct soap*, const char*, int, const struct ns__sendFileBase64 *, const char*);
SOAP_FMAC3 struct ns__sendFileBase64 * SOAP_FMAC4 soap_get_ns__sendFileBase64(struct soap*, struct ns__sendFileBase64 *, const char*, const char*);
SOAP_FMAC3 struct ns__sendFileBase64 * SOAP_FMAC4 soap_in_ns__sendFileBase64(struct soap*, const char*, struct ns__sendFileBase64 *, const char*);
SOAP_FMAC5 struct ns__sendFileBase64 * SOAP_FMAC6 soap_new_ns__sendFileBase64(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__sendFileBase64(struct soap*, struct ns__sendFileBase64*);
SOAP_FMAC3 struct ns__sendFileBase64 * SOAP_FMAC4 soap_instantiate_ns__sendFileBase64(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__sendFileBase64(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__sendFileBase64Response
#define SOAP_TYPE_ns__sendFileBase64Response (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__sendFileBase64Response(struct soap*, struct ns__sendFileBase64Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__sendFileBase64Response(struct soap*, const struct ns__sendFileBase64Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__sendFileBase64Response(struct soap*, const struct ns__sendFileBase64Response *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__sendFileBase64Response(struct soap*, const char*, int, const struct ns__sendFileBase64Response *, const char*);
SOAP_FMAC3 struct ns__sendFileBase64Response * SOAP_FMAC4 soap_get_ns__sendFileBase64Response(struct soap*, struct ns__sendFileBase64Response *, const char*, const char*);
SOAP_FMAC3 struct ns__sendFileBase64Response * SOAP_FMAC4 soap_in_ns__sendFileBase64Response(struct soap*, const char*, struct ns__sendFileBase64Response *, const char*);
SOAP_FMAC5 struct ns__sendFileBase64Response * SOAP_FMAC6 soap_new_ns__sendFileBase64Response(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__sendFileBase64Response(struct soap*, struct ns__sendFileBase64Response*);
SOAP_FMAC3 struct ns__sendFileBase64Response * SOAP_FMAC4 soap_instantiate_ns__sendFileBase64Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__sendFileBase64Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__visitURL
#define SOAP_TYPE_ns__visitURL (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__visitURL(struct soap*, struct ns__visitURL *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__visitURL(struct soap*, const struct ns__visitURL *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__visitURL(struct soap*, const struct ns__visitURL *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__visitURL(struct soap*, const char*, int, const struct ns__visitURL *, const char*);
SOAP_FMAC3 struct ns__visitURL * SOAP_FMAC4 soap_get_ns__visitURL(struct soap*, struct ns__visitURL *, const char*, const char*);
SOAP_FMAC3 struct ns__visitURL * SOAP_FMAC4 soap_in_ns__visitURL(struct soap*, const char*, struct ns__visitURL *, const char*);
SOAP_FMAC5 struct ns__visitURL * SOAP_FMAC6 soap_new_ns__visitURL(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__visitURL(struct soap*, struct ns__visitURL*);
SOAP_FMAC3 struct ns__visitURL * SOAP_FMAC4 soap_instantiate_ns__visitURL(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__visitURL(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__visitURLResponse
#define SOAP_TYPE_ns__visitURLResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__visitURLResponse(struct soap*, struct ns__visitURLResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__visitURLResponse(struct soap*, const struct ns__visitURLResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__visitURLResponse(struct soap*, const struct ns__visitURLResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__visitURLResponse(struct soap*, const char*, int, const struct ns__visitURLResponse *, const char*);
SOAP_FMAC3 struct ns__visitURLResponse * SOAP_FMAC4 soap_get_ns__visitURLResponse(struct soap*, struct ns__visitURLResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__visitURLResponse * SOAP_FMAC4 soap_in_ns__visitURLResponse(struct soap*, const char*, struct ns__visitURLResponse *, const char*);
SOAP_FMAC5 struct ns__visitURLResponse * SOAP_FMAC6 soap_new_ns__visitURLResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__visitURLResponse(struct soap*, struct ns__visitURLResponse*);
SOAP_FMAC3 struct ns__visitURLResponse * SOAP_FMAC4 soap_instantiate_ns__visitURLResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__visitURLResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ping
#define SOAP_TYPE_ns__ping (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ping(struct soap*, struct ns__ping *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ping(struct soap*, const struct ns__ping *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ping(struct soap*, const struct ns__ping *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ping(struct soap*, const char*, int, const struct ns__ping *, const char*);
SOAP_FMAC3 struct ns__ping * SOAP_FMAC4 soap_get_ns__ping(struct soap*, struct ns__ping *, const char*, const char*);
SOAP_FMAC3 struct ns__ping * SOAP_FMAC4 soap_in_ns__ping(struct soap*, const char*, struct ns__ping *, const char*);
SOAP_FMAC5 struct ns__ping * SOAP_FMAC6 soap_new_ns__ping(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__ping(struct soap*, struct ns__ping*);
SOAP_FMAC3 struct ns__ping * SOAP_FMAC4 soap_instantiate_ns__ping(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ping(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__pingResponse
#define SOAP_TYPE_ns__pingResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__pingResponse(struct soap*, struct ns__pingResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__pingResponse(struct soap*, const struct ns__pingResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__pingResponse(struct soap*, const struct ns__pingResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__pingResponse(struct soap*, const char*, int, const struct ns__pingResponse *, const char*);
SOAP_FMAC3 struct ns__pingResponse * SOAP_FMAC4 soap_get_ns__pingResponse(struct soap*, struct ns__pingResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__pingResponse * SOAP_FMAC4 soap_in_ns__pingResponse(struct soap*, const char*, struct ns__pingResponse *, const char*);
SOAP_FMAC5 struct ns__pingResponse * SOAP_FMAC6 soap_new_ns__pingResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__pingResponse(struct soap*, struct ns__pingResponse*);
SOAP_FMAC3 struct ns__pingResponse * SOAP_FMAC4 soap_instantiate_ns__pingResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__pingResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__receiveEventsStruct
#define SOAP_TYPE_ns__receiveEventsStruct (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__receiveEventsStruct(struct soap*, struct s2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__receiveEventsStruct(struct soap*, struct s2 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__receiveEventsStruct(struct soap*, const struct s2 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__receiveEventsStruct(struct soap*, const char*, int, const struct s2 *, const char*);
SOAP_FMAC3 struct s2 * SOAP_FMAC4 soap_get_ns__receiveEventsStruct(struct soap*, struct s2 *, const char*, const char*);
SOAP_FMAC3 struct s2 * SOAP_FMAC4 soap_in_ns__receiveEventsStruct(struct soap*, const char*, struct s2 *, const char*);
SOAP_FMAC5 struct s2 * SOAP_FMAC6 soap_new_ns__receiveEventsStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__receiveEventsStruct(struct soap*, struct s2*);
SOAP_FMAC3 struct s2 * SOAP_FMAC4 soap_instantiate_ns__receiveEventsStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__receiveEventsStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_s2
#define SOAP_TYPE_s2 (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_s2(struct soap*, struct s2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_s2(struct soap*, const struct s2 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_s2(struct soap*, const struct s2 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_s2(struct soap*, const char*, int, const struct s2 *, const char*);
SOAP_FMAC3 struct s2 * SOAP_FMAC4 soap_get_s2(struct soap*, struct s2 *, const char*, const char*);
SOAP_FMAC3 struct s2 * SOAP_FMAC4 soap_in_s2(struct soap*, const char*, struct s2 *, const char*);
SOAP_FMAC5 struct s2 * SOAP_FMAC6 soap_new_s2(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_s2(struct soap*, struct s2*);
SOAP_FMAC3 struct s2 * SOAP_FMAC4 soap_instantiate_s2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_s2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__receiveFileStruct
#define SOAP_TYPE_ns__receiveFileStruct (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__receiveFileStruct(struct soap*, struct s1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__receiveFileStruct(struct soap*, struct s1 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__receiveFileStruct(struct soap*, const struct s1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__receiveFileStruct(struct soap*, const char*, int, const struct s1 *, const char*);
SOAP_FMAC3 struct s1 * SOAP_FMAC4 soap_get_ns__receiveFileStruct(struct soap*, struct s1 *, const char*, const char*);
SOAP_FMAC3 struct s1 * SOAP_FMAC4 soap_in_ns__receiveFileStruct(struct soap*, const char*, struct s1 *, const char*);
SOAP_FMAC5 struct s1 * SOAP_FMAC6 soap_new_ns__receiveFileStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__receiveFileStruct(struct soap*, struct s1*);
SOAP_FMAC3 struct s1 * SOAP_FMAC4 soap_instantiate_ns__receiveFileStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__receiveFileStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_s1
#define SOAP_TYPE_s1 (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_s1(struct soap*, struct s1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_s1(struct soap*, const struct s1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_s1(struct soap*, const struct s1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_s1(struct soap*, const char*, int, const struct s1 *, const char*);
SOAP_FMAC3 struct s1 * SOAP_FMAC4 soap_get_s1(struct soap*, struct s1 *, const char*, const char*);
SOAP_FMAC3 struct s1 * SOAP_FMAC4 soap_in_s1(struct soap*, const char*, struct s1 *, const char*);
SOAP_FMAC5 struct s1 * SOAP_FMAC6 soap_new_s1(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_s1(struct soap*, struct s1*);
SOAP_FMAC3 struct s1 * SOAP_FMAC4 soap_instantiate_s1(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_s1(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__procEvent_t
#define SOAP_TYPE_ns__procEvent_t (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__procEvent_t(struct soap*, struct pe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__procEvent_t(struct soap*, struct pe const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__procEvent_t(struct soap*, const struct pe *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__procEvent_t(struct soap*, const char*, int, const struct pe *, const char*);
SOAP_FMAC3 struct pe * SOAP_FMAC4 soap_get_ns__procEvent_t(struct soap*, struct pe *, const char*, const char*);
SOAP_FMAC3 struct pe * SOAP_FMAC4 soap_in_ns__procEvent_t(struct soap*, const char*, struct pe *, const char*);
SOAP_FMAC5 struct pe * SOAP_FMAC6 soap_new_ns__procEvent_t(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__procEvent_t(struct soap*, struct pe*);
SOAP_FMAC3 struct pe * SOAP_FMAC4 soap_instantiate_ns__procEvent_t(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__procEvent_t(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_pe
#define SOAP_TYPE_pe (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pe(struct soap*, struct pe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pe(struct soap*, const struct pe *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pe(struct soap*, const struct pe *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pe(struct soap*, const char*, int, const struct pe *, const char*);
SOAP_FMAC3 struct pe * SOAP_FMAC4 soap_get_pe(struct soap*, struct pe *, const char*, const char*);
SOAP_FMAC3 struct pe * SOAP_FMAC4 soap_in_pe(struct soap*, const char*, struct pe *, const char*);
SOAP_FMAC5 struct pe * SOAP_FMAC6 soap_new_pe(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_pe(struct soap*, struct pe*);
SOAP_FMAC3 struct pe * SOAP_FMAC4 soap_instantiate_pe(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_pe(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__regEvent_t
#define SOAP_TYPE_ns__regEvent_t (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__regEvent_t(struct soap*, struct re *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__regEvent_t(struct soap*, struct re const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__regEvent_t(struct soap*, const struct re *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__regEvent_t(struct soap*, const char*, int, const struct re *, const char*);
SOAP_FMAC3 struct re * SOAP_FMAC4 soap_get_ns__regEvent_t(struct soap*, struct re *, const char*, const char*);
SOAP_FMAC3 struct re * SOAP_FMAC4 soap_in_ns__regEvent_t(struct soap*, const char*, struct re *, const char*);
SOAP_FMAC5 struct re * SOAP_FMAC6 soap_new_ns__regEvent_t(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__regEvent_t(struct soap*, struct re*);
SOAP_FMAC3 struct re * SOAP_FMAC4 soap_instantiate_ns__regEvent_t(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__regEvent_t(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_re
#define SOAP_TYPE_re (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_re(struct soap*, struct re *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_re(struct soap*, const struct re *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_re(struct soap*, const struct re *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_re(struct soap*, const char*, int, const struct re *, const char*);
SOAP_FMAC3 struct re * SOAP_FMAC4 soap_get_re(struct soap*, struct re *, const char*, const char*);
SOAP_FMAC3 struct re * SOAP_FMAC4 soap_in_re(struct soap*, const char*, struct re *, const char*);
SOAP_FMAC5 struct re * SOAP_FMAC6 soap_new_re(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_re(struct soap*, struct re*);
SOAP_FMAC3 struct re * SOAP_FMAC4 soap_instantiate_re(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_re(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__fileEvent_t
#define SOAP_TYPE_ns__fileEvent_t (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__fileEvent_t(struct soap*, struct fe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__fileEvent_t(struct soap*, struct fe const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__fileEvent_t(struct soap*, const struct fe *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__fileEvent_t(struct soap*, const char*, int, const struct fe *, const char*);
SOAP_FMAC3 struct fe * SOAP_FMAC4 soap_get_ns__fileEvent_t(struct soap*, struct fe *, const char*, const char*);
SOAP_FMAC3 struct fe * SOAP_FMAC4 soap_in_ns__fileEvent_t(struct soap*, const char*, struct fe *, const char*);
SOAP_FMAC5 struct fe * SOAP_FMAC6 soap_new_ns__fileEvent_t(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__fileEvent_t(struct soap*, struct fe*);
SOAP_FMAC3 struct fe * SOAP_FMAC4 soap_instantiate_ns__fileEvent_t(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__fileEvent_t(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fe
#define SOAP_TYPE_fe (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fe(struct soap*, struct fe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fe(struct soap*, const struct fe *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_fe(struct soap*, const struct fe *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fe(struct soap*, const char*, int, const struct fe *, const char*);
SOAP_FMAC3 struct fe * SOAP_FMAC4 soap_get_fe(struct soap*, struct fe *, const char*, const char*);
SOAP_FMAC3 struct fe * SOAP_FMAC4 soap_in_fe(struct soap*, const char*, struct fe *, const char*);
SOAP_FMAC5 struct fe * SOAP_FMAC6 soap_new_fe(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_fe(struct soap*, struct fe*);
SOAP_FMAC3 struct fe * SOAP_FMAC4 soap_instantiate_fe(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fe(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
